
// list of more than 500 words for Hangman game,
export const words = [
    "apple", "banana", "orange", "grape", "mango", "pineapple", "strawberry", "blueberry", "kiwi", "peach",
    "pear", "cherry", "lemon", "lime", "watermelon", "papaya", "guava", "apricot", "plum", "fig",
    "pomegranate", "coconut", "raspberry", "blackberry", "cranberry",
    "carrot", "broccoli", "spinach", "tomato", "potato", "onion", "garlic", "cucumber", "lettuce", "cabbage",
    "pepper", "zucchini", "eggplant", "cauliflower", "radish", "beet", "asparagus", "celery", "kale", "pumpkin",
    "squash", "turnip", "parsnip", "leek", "brussels",
    "dog", "cat", "elephant", "tiger", "lion", "bear", "wolf", "fox", "deer", "rabbit",
    "horse", "cow", "sheep", "goat", "pig", "monkey", "giraffe", "zebra", "kangaroo", "panda",
    "dolphin", "shark", "whale", "eagle", "owl", "parrot", "hawk", "falcon", "vulture", "peacock",
    "swan", "duck", "goose", "turkey", "chicken", "rooster", "penguin", "flamingo", "stork", "heron",
    "crane", "pelican", "albatross", "seagull", "kingfisher", "ostrich", "emu", "cassowary",
    "koala", "wombat", "platypus", "echidna", "sloth", "lemur", "meerkat", "hyena", "jackal", "cheetah",
    "leopard", "jaguar", "lynx", "bobcat", "cougar", "badger", "weasel", "mink", "ferret", "stoat",
    "hedgehog", "porcupine", "squirrel", "chipmunk", "beaver", "mouse", "rat", "hamster", "gerbil", "guineapig",
    "bat", "raccoon", "skunk", "opossum", "armadillo", "anteater", "aardvark", "bison", "elk", "moose",
    "reindeer", "caribou", "yak", "okapi", "tapir", "boar", "warthog", "peccary", "antelope", "gazelle",
    "book", "pen", "chair", "table", "lamp", "clock", "phone", "computer", "television", "radio",
    "camera", "watch", "bag", "umbrella", "key", "mirror", "window", "door", "bed", "sofa",
    "fridge", "oven", "microwave", "toaster", "blender",
    "algeria", "bahrain", "comoros", "djibouti", "egypt", "iraq", "jordan", "kuwait", "lebanon", "libya", "mauritania",
    "morocco", "oman", "palestine", "qatar", "saudiarabia", "somalia", "sudan", "syria", "tunisia", "unitedarabemirates", "yemen",
    "canada", "brazil", "australia", "japan", "india", "china", "russia", "germany", "france", "italy",
    "spain", "mexico", "kenya", "southafrica", "argentina", "chile", "thailand", "vietnam", "indonesia",
    "greece", "sweden", "norway", "finland",
    "doctor", "teacher", "engineer", "lawyer", "chef", "pilot", "nurse", "artist", "writer", "musician",
    "scientist", "farmer", "soldier", "policeman", "firefighter", "dentist", "architect", "accountant", "journalist",
    "photographer", "designer", "programmer", "electrician", "plumber", "mechanic",
    "river", "mountain", "forest", "desert", "ocean", "lake", "valley", "canyon", "waterfall", "volcano",
    "island", "beach", "cave", "cliff", "glacier", "plain", "meadow", "swamp", "tundra", "savanna",
    "jungle", "reef", "delta", "fossil", "geyser",
    "soccer", "basketball", "tennis", "golf", "swimming", "boxing", "wrestling", "cricket", "hockey", "volleyball",
    "baseball", "rugby", "cycling", "skiing", "surfing", "running", "judo", "karate", "fencing", "archery",
    "tabletennis", "badminton", "gymnastics", "weightlifting", "rowing",
    "shirt", "pants", "dress", "jacket", "coat", "hat", "scarf", "gloves", "shoes", "socks",
    "belt", "tie", "sweater", "skirt", "boots", "vest", "hoodie", "cap", "sneakers", "sandals",
    "shorts", "tshirt", "blouse", "overcoat", "raincoat",
    "music", "painting", "dance", "movie", "game", "school", "hospital", "church", "bridge", "tower",
    "castle", "train", "plane", "ship", "car", "bicycle", "garden", "park", "library", "museum",
    "jewelry", "coin", "stamp", "map", "compass", "telescope", "microscope", "robot", "rocket", "satellite",
    "guitar", "piano", "drum", "violin", "flute", "trumpet", "saxophone", "harmonica", "accordion", "banjo",
    "lens", "brush", "canvas", "paper", "pencil", "eraser", "ruler", "scissors", "tape", "penny",
    "dollar", "euro", "yen", "pound", "gold", "silver", "bronze", "diamond", "ruby", "emerald",
    "sapphire", "pearl", "coral", "shell", "feather", "leaf", "stone", "sand", "cloud", "rain",
    "snow", "wind", "sun", "moon", "star", "planet", "galaxy", "comet", "asteroid", "butterfly",
    "dragonfly", "ladybug", "ant", "bee", "spider", "snake", "lizard", "frog", "turtle", "crocodile",
    "alligator", "hippo", "rhino", "buffalo", "camel", "llama", "donkey", "mule", "otter", "seal",
    "walrus", "pigeon", "dove", "crow", "raven", "magpie", "sparrow", "finch", "robin", "bluejay",
    "cardinal", "woodpecker", "hummingbird", "impala", "oryx", "addax", "ibex", "markhor", "goral", "serow",
    "chamois", "takin", "mouflon", "springbok", "hartebeest", "wildebeest", "waterbuck", "kudu", "eland", "sable",
    "roan", "bontebok", "lechwe", "sassaby", "topi", "tsessebe", "nyala", "bushbuck", "sitatunga", "bongo",
    "duiker", "dikdik", "klipspringer", "reedbuck", "grysbok", "steenbok", "oribi", "sunni", "gerenuk", "beira",
    "saiga", "coffee", "tea", "juice", "milk", "water", "bread", "cheese", "butter", "sugar", "salt",
    "honey", "jam", "flour", "rice", "pasta", "noodle", "soup", "salad", "pizza",
    "burger", "sandwich", "cake", "cookie", "chocolate", "candy", "icecream", "yogurt", "cream", "syrup",
    "vinegar", "oil", "mustard", "ketchup", "mayonnaise", "egg", "bacon", "sausage", "steak",
    "fish", "shrimp", "crab", "lobster", "salmon", "tuna", "sardine", "cod", "trout", "mackerel",
    "city", "village", "town", "street", "road", "path", "highway", "tunnel", "dam", "fence",
    "gate", "wall", "roof", "floor", "ceiling", "stairs", "elevator", "escalator", "chimney", "balcony"
];
